# Generated by Django 5.1.3 on 2024-11-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.CharField(max_length=100)),
                ('customer_phone', models.IntegerField()),
                ('customer_address', models.CharField(max_length=200)),
                ('customer_city', models.CharField(max_length=100)),
            ],
        ),
    ]
